In [2]:
import numpy as np

In [ ]:

list = [1, 2, 36667]
print(type(list))

np_list = np.array(list)
print(type(np_list))


<class 'list'>
<class 'numpy.ndarray'>


In [6]:
np_list.dtype

dtype('int32')

In [7]:
np_list.shape

(3,)

In [8]:
np_list.ndim

1

In [11]:
""" 
Create an Array with all zeros

"""

zeros_np_array = np.zeros(shape= (5,))
print(zeros_np_array.dtype)
zeros_np_array

float64


array([0., 0., 0., 0., 0.])

In [14]:
""" 
Create an Array with all ones

"""

ones_np_array = np.ones(shape= (10, 2), 
                        dtype= int)

print(ones_np_array.dtype)
ones_np_array

int32


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [16]:
""" 
Create an Array assigned with a specific value

"""

np_array_assign_with_specific_values = np.full(
    shape= (5,),
    dtype= int,
    fill_value= 15,
    )

print(np_array_assign_with_specific_values.dtype)

np_array_assign_with_specific_values

int32


array([15, 15, 15, 15, 15])

In [ ]:
"""
Create an Identity Matrix
[1,0,0]
[0,1,0]
[0,0,1]
I3
"""
id_matrix = np.eye(4)
print(id_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
"""
Create an empty array
"""

np_empty_array = np.empty(
    shape= (5,)
)
np_empty_array

array([0., 0., 0., 0., 0.])

In [24]:
"""Type Cast
Conversion from one data type to another compatible data type
"""
print(np_empty_array.dtype)
np_empty_array_int = np_empty_array.astype('int')
print(np_empty_array_int)
print(np_empty_array_int.dtype)

float64
[0 0 0 0 0]
int32


In [4]:
"""Create Sequential array
"""
np_seq_array = np.arange(start= 1, stop= 10)
np_seq_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
"""Create Sequential array
"""
np_seq1_array = np.arange(start= 1, stop= 10, step= 2)
np_seq1_array

array([1, 3, 5, 7, 9])

In [6]:
"""Create a linearly spaced array
start = 0
stop = 10
num = 5 

0  2.5   5   7.5   10
"""
np_lin_spaced_array = np.linspace(start= 0, 
                                  stop= 10, 
                                  num= 5  )
np_lin_spaced_array

array([ 0. ,  2.5,  5. ,  7.5, 10. ])